# Generated by Django 5.1.4 on 2024-12-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
    ]
